FROM ubuntu:cosmic

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get clean
RUN apt-get update && apt-get upgrade
RUN apt-get install -y python3.7 python3.7-dev python3.7-venv python3-pip git xorg-dev ruby-dev lua5.1 liblua5.1-dev libperl-dev git gdb netcat

RUN git clone https://github.com/wilvk/vader.vim.git /root/.vim/plugin/vader.vim
RUN git clone https://github.com/vim/vim.git /opt/vim_sources

RUN cd /opt/vim_sources && \
    ./configure --disable-netbeans --enable-cscope --enable-fail-if-missing --enable-fontset --enable-gui=auto --enable-largefile --enable-luainterp=yes \
                --enable-multibyte --enable-perlinterp=yes --enable-python3interp=yes --enable-rubyinterp=yes --with-features=huge --with-python3-command=python3.7 \
                --with-python3-config-dir=/usr/lib/python3.7/config-3.7m-x86_64-linux-gnu --with-x && \
    make && make install
