#!/bin/bash

set -x

CURRENT_PATH=${PWD##*/}
DOCKER_IMAGE_NAME=$CURRENT_PATH-daemon

echo "Docker image name: ${DOCKER_IMAGE_NAME}"
docker build -t ${DOCKER_IMAGE_NAME} -f ./Dockerfile-daemon .
docker run -it -d -p 9999:9999 -v $PWD:/$CURRENT_PATH --security-opt seccomp=unconfined --workdir=/$CURRENT_PATH ${DOCKER_IMAGE_NAME} bash -c "./start-server $1"
