FROM ubuntu:xenial

ENV \
    DEBIAN_FRONTEND=noninteractive \
    TERM=xterm

RUN \
    apt-get update && \
    apt-get install -y git

RUN \
    apt-get update && \
    apt-get install -y libncurses5-dev libgnome2-dev libgnomeui-dev \
    libgtk2.0-dev libatk1.0-dev libbonoboui2-dev \
    libcairo2-dev libx11-dev libxpm-dev libxt-dev

RUN \
    apt-get update && \
    apt-get install -y python python-dev python-pip python-virtualenv && \
    rm -rf /var/lib/apt/lists/*

RUN \
    apt-get update && \
    apt-get install -y ruby-full && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    apt-get autoremove -y && \
    apt-get clean

RUN git clone --depth 1 https://github.com/vim/vim /root/vim

RUN apt-get update && \
    apt-get install -y libpython3.5-dev

RUN rm /usr/bin/python && ln -s /usr/bin/python3.5 /usr/bin/python

RUN cd /root/vim && \
    ./configure --with-features=huge \
                --enable-cscope \
                --enable-gnome-check \
                --enable-gtk2-check \
                --enable-gui=auto \
                --enable-multibyte \
                --enable-rubyinterp \
                --enable-python3interp \
                --enable-pythoninterp \
                --with-python-config-dir=/usr/lib/python3.5/config \
                --with-python3-config-dir=/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu \
                --enable-perlinterp \
                --enable-luainterp \
                --enable-gui=gnome2 \
                --enable-cscope \
                --with-x && \
    make && \
    make install

RUN gem install rspec

RUN touch /root/.Xauthority

RUN apt-get update && apt-get install -y gdb
