version: "3"

services:

  dev-server:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-server
    working_dir: /work
    security_opt:
      - seccomp:unconfined
    ports:
      - "9999:9999"
    environment:
      - BINARY_TO_RUN
    volumes:
      - ..:/work
      - ${BINARY_LOCATION}:/binaries
    command: /work/scripts/start-server

