FROM ubuntu:xenial

ENV \
    DEBIAN_FRONTEND=noninteractive \
    TERM=xterm

RUN \
    apt-get update && \
    apt-get install -y vim

RUN \
    apt-get update && \
    apt-get install -y python python-dev python-pip python-virtualenv && \
    rm -rf /var/lib/apt/lists/*

RUN \
    apt-get update && \
    apt-get install -y ruby-full && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    apt-get autoremove -y && \
    apt-get clean
