# Vgdb subsystem plugin config spec:

windows:
  - window_name:
      type: [stackable|abutted|either]
      height: nn
      width: nn
      query: [string]
      filter:
        - filter1: [regex string - e.g. to strip out unwanted characters and lines]
        - filter2: ...
      updatable: [y|n,1|0]
      update_on_each_query: [y|n,1|0]
      update_on_query: [regex string of query]
      max_results: nn
      expect: [string]
      error: [regex string]
      module: [module name string]
modules:
  - module_name:
      startup_command: [string]
      filter:
      expect:
      error:
      log:
loggers:
  - logger_name:
      script_file:
      script:
      default_log_value:
      timestamp:
      filter:
window_handles:
  - window_name:
      window:
      script_file:
      script:
