# Vgdb subsystem plugin config spec:

windows:
  - window_name:
      type: [stackable|abutted|either]
      height: nn
      width: nn
      query: [string]
      filter:
        - vg_name:
          regex:
          type:
          description:
      updatable: [y|n,1|0]
      update_on_each_query: [y|n,1|0]
      update_on_query: [regex string of query]
      max_results: nn
      expect: [string]
      error: [regex string]
      module: [module name string]
      depends_on:
command:
   - command_name:
       run_on_command_before_command: file.py#function(command) returns string or bool
       run_on_command_after_command:  same as above
       run_on_lines_after_command: file.py#function(linesp[) returns lines[]
modules:
  - module_name:
      startup_command: [string]
      filter:
      expect:
      error:
      log:
loggers:
  - logger_name:
      script_file:
      script:
      default_log_value:
      timestamp:
      filter:
events:
  - event_name:
      subscriber: [name of buffer to update when an event occurs]
window_handles:
  - window_name:
      window:
      script_file:
      script:
