#! /bin/bash

unset BUNDLE_PATH
unset BUNDLE_BIN

BASE_PATH=/root/.gvim/plugin/vgdb

cd $BASE_PATH/tests/vimrunner

bundle install

gem build vimrunner.gemspec

gem install vimrunner-0.3.4.gem

cd $BASE_PATH/tests

rspec spec/test_buffers.rb
